### ISSUE TITLE
Missile script calculations wrong

### ISSUE THREAD

**Issue by thorr18** [DarkFenX/Pyfa#409] opened 2015-11-06 18:44 UTC
<img width="930" alt="screen shot 2015-11-06 at 10 33 04 am" src="https://cloud.githubusercontent.com/assets/3753521/11005591/6eca9bf6-8473-11e5-98a4-582fbc7499a7.png">
Calculations are different between 1.15 & 1.16. for missile range , explosion velocity, & explosion radius. 
I'll attach screenshot. 
The missile guidance computer II can have a charge with -100% to range effect or a different charge with -100% explosion velocity effect. These script charges appear to have the expected effect when toggling the module on and off on the previous version. On the newer version, I see values that should not change (because of the -100%) change when the module is toggled.

**Comment by blitzmann** [comment] 2015-11-06 19:47
Duplicate of #404 and #406. Already been fixed in the repo.

**Closed by blitzmann** 2015-11-06 19:47 UTC

**Comment by thorr18** [comment] 2015-11-06 20:00
My mistake for only searching open issues before posting a new one.
