### ISSUE TITLE
Market pricing broken in pyfa 1.14.0-galatea-1.2-win

### ISSUE THREAD

**Issue by dvallis** [DarkFenX/Pyfa#350] opened 2015-08-30 23:40 UTC
Uninstalled previous version of Pyfa (1.13.2)
Deleted c:\users\xxxx\.pyfa directory
Downloaded & installed pyfa 1.14.0-galatea-1.2-win.exe
Market pricing now broken. Will not update for ships or eqipment
Reinstalled 1.13.2. Pricing broken in that as well. Was previously working.

???

![image](https://cloud.githubusercontent.com/assets/5086218/9570134/75417a16-4f46-11e5-8974-02e51fd117d9.png)

**Comment by blitzmann** [comment] 2015-08-31 01:04
It's an issue with EVE Central's API. It seems to be broken for some reason and returning `0.0` for multiple items. Out of our hands, however I'll leave this open in case anyone else looks here for answers.

Also, I'm hoping you backed up the user database in `.pyfa` before deleting it. =x

**Comment by blitzmann** [comment] 2015-08-31 22:02
EVEs CREST servers were down for a while, but it looks like the problem is fixed on their end. EVE Central is now reporting correct values.

**Closed by blitzmann** 2015-08-31 22:02 UTC
