### ISSUE TITLE
Issue with Capacitor Flux Coils.

### ISSUE THREAD

**Issue by Neugeniko** [DarkFenX/Pyfa#399] opened 2015-11-04 01:30 UTC
The following error occurs when loading a fit with a capacitor flux coil or trying to add the module to a fit.

2015-11-04 03:02:44,515 root                     INFO     Starting pyfa
2015-11-04 03:03:35,238 service.fit              DEBUG    ==========recalc==========
2015-11-04 03:03:36,146 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=377, ship=Sleipnir, name=Nir - Neug NEW) at 0xafd0eeacL, withBoosters: True
2015-11-04 03:03:36,395 eos.saveddata.fit        DEBUG    Timer - Fit: 377, Nir - Neug NEW - Done with runtime: early - 249.06ms (249.07ms elapsed)
Traceback (most recent call last):
  File "/home/neugeniko/src/pyfa/gui/builtinViews/fittingView.py", line 65, in fitSelected
    view.fitSelected(event)
  File "/home/neugeniko/src/pyfa/gui/builtinViews/fittingView.py", line 287, in fitSelected
    self.slotsChanged()
  File "/home/neugeniko/src/pyfa/gui/builtinViews/fittingView.py", line 439, in slotsChanged
    self.generateMods()
  File "/home/neugeniko/src/pyfa/gui/builtinViews/fittingView.py", line 396, in generateMods
    fit = sFit.getFit(self.activeFitID)
  File "/home/neugeniko/src/pyfa/service/fit.py", line 254, in getFit
    self.recalc(fit, withBoosters=True)
  File "/home/neugeniko/src/pyfa/service/fit.py", line 1000, in recalc
    fit.calculateModifiedAttributes(withBoosters=withBoosters)
  File "/home/neugeniko/src/pyfa/eos/saveddata/fit.py", line 510, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "/home/neugeniko/src/pyfa/eos/saveddata/module.py", line 602, in calculateModifiedAttributes
    effect.handler(fit, self, context)
  File "/home/neugeniko/src/pyfa/eos/effects/shieldcapacitymultiply.py", line 12, in handler
    fit.ship.multiplyItemAttr("shieldCapacity", module.getModifiedItemAttr("shieldCapacityMultiplier"))
  File "/home/neugeniko/src/pyfa/eos/effectHandlerHelpers.py", line 247, in multiplyItemAttr
    self.itemModifiedAttributes.multiply(*args, **kwargs)
  File "/home/neugeniko/src/pyfa/eos/modifiedAttributeDict.py", line 303, in multiply
    self.__multipliers[attributeName] *= multiplier
TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'
2015-11-04 03:03:36,875 service.fit              DEBUG    ==========recalc==========
2015-11-04 03:03:36,878 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=377, ship=Sleipnir, name=Nir - Neug NEW) at 0xafd0eeacL, withBoosters: True
2015-11-04 03:03:36,909 eos.saveddata.fit        DEBUG    Timer - Fit: 377, Nir - Neug NEW - Done with runtime: early - 31.46ms (31.47ms elapsed)

**Comment by OISumeko** [comment] 2015-11-04 01:32
Related/Duplicate of #397

**Comment by blitzmann** [comment] 2015-11-04 01:40
Aye. Closing

**Closed by blitzmann** 2015-11-04 01:40 UTC
