### ISSUE TITLE
Missing icon files

### ISSUE THREAD

**Issue by thorr18** [DarkFenX/Pyfa#452] opened 2015-11-30 08:20 UTC
Don't know if this is of interest, but I sometimes see missing icon messages on the terminal: 
~~~
Nov 29 23:51:56  pyfa[7459] <Notice>: 2015-11-29 23:51:56,006 STDOUT                   INFO     Missing icon file from zip: icons/res:/ui/texture/icons/109_64_1.png.png
~~~
~~~
Nov 30 00:00:16  pyfa[7459] <Notice>: 2015-11-30 00:00:16,354 STDOUT                   INFO     Missing icon file from zip: icons/res:/ui/texture/icons/109_64_2.png.png
~~~
~~~
Nov 30 00:09:00  pyfa[7459] <Notice>: 2015-11-30 00:09:00,940 STDOUT                   INFO     Missing icon file from zip: icons/.png
~~~

**Comment by blitzmann** [comment] 2015-11-30 17:49
Some missing icon messages are normal and to be expected, because they just don't exist (for example, it seems to be the case for that last one). However, there are times when CCP introduces new icons (such as the new HIC point icon) and we forget to add them.

CCP has also been known to change the formate of the icon path, so that might be whats going on in the first and second example. Do you know what market group you looked at or fit you opened to spawn these messages?

**Comment by thorr18** [comment] 2015-12-02 10:06
The micro jump field generators category icon causes this one (not the generator, but the generators category): 
~~~
Dec  2 02:04:23  pyfa[8760] <Notice>: 2015-12-02 02:04:23,422 STDOUT                   INFO     Missing icon file from zip: icons/.png
~~~

**Comment by thorr18** [comment] 2015-12-02 10:14
This one is for Rapid Heavy Missile Launchers category: 
~~~
Dec  2 02:12:14  pyfa[8766] <Notice>: 2015-12-02 02:12:14,746 STDOUT                   INFO     Missing icon file from zip: icons/res:/ui/texture/icons/109_64_1.png.png
~~~

**Comment by thorr18** [comment] 2015-12-02 10:24
This comes from when viewing the six items under 'Warp Disruption Fields'
~~~
Dec  2 02:22:21  pyfa[8775] <Notice>: 2015-12-02 02:22:21,209 STDOUT                   INFO     Missing icon file from zip: icons/36_15.png
~~~

**Comment by thorr18** [comment] 2015-12-02 10:49
From the five items under 'Warp Disruption Field Generators'
~~~
Dec  2 02:48:01  pyfa[8791] <Notice>: 2015-12-02 02:48:01,507 STDOUT                   INFO     Missing icon file from zip: icons/118_2.png
~~~

**Comment by thorr18** [comment] 2015-12-02 10:57
'Bastion Module I'
~~~
Dec  2 02:56:43  pyfa[8794] <Notice>: 2015-12-02 02:56:43,593 STDOUT                   INFO     Missing icon file from zip: icons/res:/ui/texture/icons/109_64_2.png.png
~~~

**Comment by blitzmann** [comment] 2015-12-06 15:35
Yeah, just had to update all the icons to the december release, which introduced a few new ones. Some of these were also caused by a bug in the icon conversion code. Should be fixed with the latest sisi commit https://github.com/DarkFenX/Pyfa.git

**Closed by blitzmann** 2015-12-06 15:35 UTC
