### ISSUE TITLE
Copying Fit Doesn't Work / Breaks Loading Loadouts

### ISSUE THREAD

**Issue by droppedoncaprica** [DarkFenX/Pyfa#285] opened 2015-05-03 23:29 UTC
Search for a ship with a fit already saved.  On the fit, click the green `+` icon.  The fit won't duplicate.  After it is clicked, you can no longer load fits that have been saved.

I'm on Windows 10 on the `wx3` release.

**Comment by blitzmann** [comment] 2015-05-06 04:40
I cannot reproduce with the current wx3 branch on interpreter, however this does happen with the pre-release binary.

**Comment by droppedoncaprica** [comment] 2015-05-06 12:49
I'll double-check what version of Pyfa I have installed tonight and see if there is a newer build.

**Comment by blitzmann** [comment] 2015-06-20 17:47
Closing issue - still cannot reproduce. reopen if you experience the issue again

**Closed by blitzmann** 2015-06-20 17:47 UTC
Labels: wx3
