### ISSUE TITLE
Price update

### ISSUE THREAD

**Issue by unti1x** [DarkFenX/Pyfa#290] opened 2015-05-17 10:57 UTC
1. "Updating prices..." label disappears after first response
When price request for the first module started, label is being shown, then disappears after response. Next requests being processed without it.

2. Prices not changing for another fit
Open any fitting and wait for price update. Open another one for any other ship - prices not changing until update finished. They may never change if API error happened.

**Comment by blitzmann** [comment] 2015-05-20 07:29
1. I've noticed that there is a bit of a lag period where the updating price label disappears while prices are still being fetched. I can look into this more, but honestly I'm not too concerned about it and it might be a bigger headache depending on how it actually works. Another thing to remember is that prices are cached for 4 hours, so you may not see the message because of this.

2. Prices are queued based on the order they were requested. so if fit 1 is not done updating prices, fit 2 has to wait. This is just a byproduct of how its developed.

You bring up the issue of prices not showing up, especially if there is a network error preventing them from updating. Old prices are cached in the database, but I don't believe this cached price is used if the cache time is overdue for another update. I believe pyfa may wipe out the price info when it sees it's out of date, rather then checking for a new price and then updating. If this is the case, it's an oversight made, probably when I tidied up the pricing code. I can look into this as well, but it's fairly low on the priority list.

Also, I do not remember how pyfa works with respect to prices in memory. In addition to a database cache, there is a memory cache. It may be that pyfa will never update the price if pyfa itself never closes because it sees a price in it's memory cache. Again, will have to look into that and refresh my own memory =)

**Comment by unti1x** [comment] 2015-05-25 07:32
Actually, it's possible to request prices from eve-central for all modules at once.

**Comment by blitzmann** [comment] 2015-06-04 12:54
I know, and it would be great to use it. The only problem is that we're currently working on code that is 5+ years old and largely written by others (I've been with the project for only a year). 

The way price fetching works is that the GUI code asks the price service for the price of an item. The price service then checks the cache and asks the network service to gather the data from evecentral if the cache is old. To complicate the issue, there are two locations that ask for price: the price column in the fitting window, and the price pan in the stats area. The price service supports gathering a list of prices, and IIRC it is utilized with the price pane. But the column price fetch only knows about that one module, and so it goes through the list of modules and asks for the price separately. It's something that I wanted to look at when rewriting the price and network service but never got around to, and it's low on the priority list considering it does work, albeit inefficiently.

**Comment by blitzmann** [comment] 2015-06-05 04:09
Worked on the issue of my previous comment a bit today. So now the column prices are basically stored in a dict and await the price fetch from the price pane which requests all prices for the fit in one request. This is sort of hackish, but it works really well. The issue with implementing it properly was that each individual request had a callback that it couldn't easily be decoupled from, so it's difficult to just add the individual price requests to a pool.

But anyway, that's done. I have some time the next few days to get some of this low hanging fruit, maybe I can flesh out the Updating label to actually show without issues

**Comment by blitzmann** [comment] 2015-06-05 20:45
So I removed most of the fluff that was making the price pane more complicated than needed. Now it asks for a request, and doesn't remove the Updating... message until it hits the processing stage. I would like for that label to be attached directly to the `fetchPrices` function at the service level so that whenever anything calls it it will show. But at the moment the only thing that does call it is the price pane and it's easier to implement there.

I have also confirmed that if the update fails, pyfa DOES NOT fall back to the cached value. Instead it simply clears the value. I intend to change this, and maybe make the price red for the module indicating that we're working off out of date price information

**Comment by blitzmann** [comment] 2015-07-03 06:42
Committed my improvements to master. Next release should be Tues / Wed next week, please check it out and let me know if you notice anything off...

- Modules are queued and fetched all a once
- Refresh icon shown in price column when item is being fetched.
- Updating Prices label should be more consistent.
- If there is an error with fetching prices, use old price. `(!)` is shown in after old price

**Closed by blitzmann** 2015-07-03 06:42 UTC
