### ISSUE TITLE
Projection of Oneiros with Remote Tracking Computer does not include the ship's bonus

### ISSUE THREAD

**Issue by sdack** [DarkFenX/Pyfa#374] opened 2015-10-04 07:54 UTC
Hello,

I've been trying to figure out the effect of the Oneiros' remote tracking computers onto a turret ship like the Kronos and the Vindicator. I believe the Oneiros' ship bonus (to the effectiveness of remote tracking computers) does not get applied in the projection.

How I have tested it: I've created a fit for the Oneiros with a single remote tracking computer and all skills 5 and pulled it into the "Projected" tab of a Kronos. I did the same with a single remote tracking computer out of the market group (the same one as on the Oneiros). When I toggle the projected effect do both projections show an increase in range (both use an optimal range script), but the increased ranges are the same. Due to the bonus should the Oneiros give a higher increased range compared to an unbonused ship.

Could you please check if that is indeed a bug?

Pyfa version is: 1.15.0

**Comment by blitzmann** [comment] 2015-10-04 14:25
I cannot reproduce. I have a retribution with small lasers, with base tracking of `0.155`. If I add a remote tracking computer II with a tracking script, it adds 30% with a resultant of `0.201`. If I add an oneiros with the same module and same charge (only thing on the fit), it gives me a 45% boost to `0.224`. So the Oneiros is giving the proper stats according to my testing. All fits tested are set to All 5 character.

![1](https://cloud.githubusercontent.com/assets/3904767/10268283/ce7faa98-6a81-11e5-9134-0a0f2626565d.PNG)
![2](https://cloud.githubusercontent.com/assets/3904767/10268285/ce805a6a-6a81-11e5-8b8e-2c52b8a8f8d1.PNG)
![3](https://cloud.githubusercontent.com/assets/3904767/10268284/ce800f42-6a81-11e5-933c-e27183ea7dfd.PNG)

If you still can't get it to display the correct value, double check things like implants, fleet boosters, and skills/character. It could very well be a problem with the order the modules are run as we have had issues with that before, but usually for very edge-case scenarios. If you can, I would like you to post the fits that you are using along with screenshots if possible of module order from both fits.

Thanks =)

**Comment by sdack** [comment] 2015-10-05 15:53
Hello,
I have done what you did and I can confirm that it does indeed work for the Retribution. However, I seem to have found a case where it does not. I have created a clean test case:
Oneiros, with only a single Remote Tracking Computer II (Optimal Range script)Kronos, with a single Neutron Blaster II
When both fits are set to "All 5" then the range on the blaster changes to:9km+18.8km -> 10.3km+24.4km, for a single Remote Tracking Computer II (Optimal Range script)9km+18.8km -> 11km+27.2km, for the Oneiros
So there it is working.
When I set Kronos fitting from "All 5" to my character then this happens:9km+18.8km -> 10.3km+24.4km, for a single Remote Tracking Computer II
9km+18.8km -> 10.3km+24.4km, for the Oneiros

Here it is not working. Now, I can fly the Kronos, but I cannot fly the Oneiros, which is why I left the Oneiros fit to "All 5". Is it possible that it tries to apply my character's skills to the Oneiros fit for the projection, too? This is the only reasonable explanation that I have for it not applying the Oneiros' bonus.

 Cheers


     On Sunday, 4 October 2015, 15:25, blitzmann <notifications@github.com> wrote:
   

 I cannot reproduce. I have a retribution with small lasers, with base tracking of 0.155. If I add a remote tracking computer II with a tracking script, it adds 30% with a resultant of 0.201. If I add an oneiros with the same module and same charge (only thing on the fit), it gives me a 45% boost to 0.224. So the Oneiros is giving the proper stats according to my testing. All fits tested are set to All 5 character.

If you still can't get it to display the correct value, double check things like implants, fleet boosters, and skills/character. It could very well be a problem with the order the modules are run as we have had issues with that before, but usually for very edge-case scenarios. If you can, I would like you to post the fits that you are using along with screenshots if possible of module order from both fits.Thanks =)—

**Comment by blitzmann** [comment] 2015-10-05 16:49
Can you please e-mail api details for the character you are having a problem with? Please only include skill access for the api.

sable.blitzmann@gmail.com

**Comment by blitzmann** [comment] 2015-10-05 17:02
Actually, I have reproduced the issue using All 0, and it is very weird. A quick debug statement in the fit calculation logic shows that the Kronos is being calculated with the All 0 character, while the Onerios is being calculated with the All 5 character.

Looking at the stats of the RTC on the Onerios with All 5 shows that it should be giving 22.5% boost to optimal range and 45% boost to Falloff, but when it's applied to the Kronos it's only 15% and 30% respectively.

It might be possible that the ship bonuses aren't being applied before the module is projected...

**Comment by blitzmann** [comment] 2015-10-05 17:12
I made a new character with All 0 and set Logistics to lvl 3 and applied it to the Kronos, which boosted the Oneiros projection correctly. So it does seem that the projections are taking the target fit's character for whatever reason. It doesn't make sense to me, but it seems you were correct. =)

I'll take a look at it in the coming days

**Comment by blitzmann** [comment] 2015-10-05 22:22
I think I found out what was happening. The target fit was being registered as the RTC II's fit in it's modified attributes, and when trying to modify the attribute based on the logistics skill, it used the wrong fit's character. Should be fixed, but I'm going to make a pre-release soonish due to this change and another that affect fit calculations. I want more scenarios tested

**Comment by sdack** [comment] 2015-10-05 23:54
Thanks, it is much appreciated. I have downloaded 1.15.1 from GitHub and tested 
it - it works for me :)

**Comment by blitzmann** [comment] 2015-10-06 00:39
Sweet, will close this for now. If I find issues in the fixes, I'll revert and reopen.

**Closed by blitzmann** 2015-10-06 00:39 UTC
