### ISSUE TITLE
pyfa-1.16.2 -mac-wx3 doesn't start on macosx 10.9.5

### ISSUE THREAD

**Issue by yshestakov** [DarkFenX/Pyfa#449] opened 2015-11-28 21:29 UTC
ImportError - wx/_core_.so, 2): Symbol not found: _OBJC_CLASS_$_NSURLRequest
```
user@mac ~> Downloads/pyfa-1.16.2-wx3.app/Contents/MacOS/pyfa ; exit;
Nov 28 23:23:02 macbook pyfa[79970] <Notice>: Traceback (most recent call last):
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "/Users/user/Downloads/pyfa-1.16.2-wx3.app/Contents/Resources/__boot__.py", line 355, in <module>
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:     _run()
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "/Users/user/Downloads/pyfa-1.16.2-wx3.app/Contents/Resources/__boot__.py", line 336, in _run
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:     exec(compile(source, path, 'exec'), globals(), globals())
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "/Users/user/Downloads/pyfa-1.16.2-wx3.app/Contents/Resources/pyfa.py", line 99, in <module>
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:     import wx
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "wx/__init__.pyc", line 45, in <module>
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "wx/_core.pyc", line 4, in <module>
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "wx/_core_.pyc", line 14, in <module>
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   File "wx/_core_.pyc", line 10, in __load
Nov 28 23:23:02 macbook pyfa[79970] <Notice>: ImportError: dlopen(/Users/user/Downloads/pyfa-1.16.2-wx3.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Symbol not found: _OBJC_CLASS_$_NSURLRequest
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   Referenced from: /Users/user/Downloads/pyfa-1.16.2-wx3.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:   Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
Nov 28 23:23:02 macbook pyfa[79970] <Notice>:  in /Users/user/Downloads/pyfa-1.16.2-wx3.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
Nov 28 23:23:03 macbook pyfa[79970] <Notice>: 2015-11-28 23:23:03.021 pyfa[79970:507] pyfa Error

```

**Comment by blitzmann** [comment] 2015-11-28 22:16
Thanks for the bug report, but it's a duplicate of #395, and it has been fixed internally. I won't be releasing another 1.16 with the fix, but 1.17 should work. In the meantime, use the non-wx3 release.

Also, please check the current pre-release which include many OSX fixes as well as the December changes on SISI. =)

**Closed by blitzmann** 2015-11-28 22:16 UTC
