### ISSUE TITLE
Opening Rigs Group Gives Error

### ISSUE THREAD

**Issue by droppedoncaprica** [DarkFenX/Pyfa#284] opened 2015-05-03 22:08 UTC
![error](https://cloud.githubusercontent.com/assets/1487206/7447176/d45434c8-f1b6-11e4-9638-4600d55b9a71.png)

I'm on Windows 10 on the `wx3` release.  You can get this to happen by opening the program, then in the Market tab clicking the plus sign on Rigs.

**Comment by Roesjka** [comment] 2015-05-10 00:18
I can confirm this on Windows 10. On Debian 8 (jessie) no such issues.

**Comment by blitzmann** [comment] 2015-05-10 16:28
Also Win7 x64

**Comment by MagicFish1990** [comment] 2015-05-15 18:40
It happened for a long time on Linux.

**Comment by blitzmann** [comment] 2015-06-04 21:51
k, this is because libpng does more checking. no one really seems to know what to do about this error besides fixing the pngs (which apparently have some incorrect color profiles, whatever that means). I'll look into updating pngs (not sure which one throws the error), and as a last resort just kill the error.

**Comment by blitzmann** [comment] 2015-06-04 22:30
k, should be fixed in wx3 branch. I didn't know which icon(s) were causing problems, so I just ran all png's through `find . -type f -name "*.png" -exec convert {} {} \;` which seems to be the method everyone uses for this.

**Closed by blitzmann** 2015-06-04 22:30 UTC
Labels: wx3
