### ISSUE TITLE
freighters do not apply CPU reduction to bulkheads

### ISSUE THREAD

**Issue by sup3rb** [DarkFenX/Pyfa#412] opened 2015-11-06 22:11 UTC
freighters do not apply CPU reduction to bulkheads

**Comment by blitzmann** [comment] 2015-11-06 23:31
Duplicate of #404 and #406. Already been fixed in the repo. I will be planning a new release in the next few days after I figure out some linux bugs.

**Closed by blitzmann** 2015-11-06 23:31 UTC
