### ISSUE TITLE
Cap Boosters behaving oddly

### ISSUE THREAD

**Issue by JoshuaNotowitz** [DarkFenX/Pyfa#211] opened 2014-12-02 00:10 UTC
i noticed this unusual behavior while fitting a dread:

With both cap boosters running the cap lasts: 7m18s
![screen shot 2014-12-01 at 8 25 22 am](https://cloud.githubusercontent.com/assets/8390690/5249897/f35d875a-793b-11e4-8ea2-901185e68472.png)

With one cap booster OH the caps lasts longer as expected at: 8m48s
![screen shot 2014-12-01 at 8 25 47 am](https://cloud.githubusercontent.com/assets/8390690/5249895/f35bf0ac-793b-11e4-8552-342ee78ce5e0.png)

Unusually with both cap boosters OH the cap lasts less that is does with one OH even though the cap regen is higher the cap only lasts:8m20s
![screen shot 2014-12-01 at 8 26 00 am](https://cloud.githubusercontent.com/assets/8390690/5249896/f35cdf4e-793b-11e4-8ec8-aaeaa6a8d909.png)

[edit-blitzmann] EFT:

    [Moros, Moros fit]

    Energized Adaptive Nano Membrane II
    Energized Adaptive Nano Membrane II
    Capital Inefficient Armor Repair Unit
    Magnetic Field Stabilizer II
    Magnetic Field Stabilizer II
    Magnetic Field Stabilizer II
    Damage Control II

    Heavy Capacitor Booster II, Navy Cap Booster 800
    Heavy Capacitor Booster II, Navy Cap Booster 800
    Tracking Computer II, Optimal Range Script
    Tracking Computer II, Optimal Range Script
    Sensor Booster II, Scan Resolution Script

    Siege Module II
    Limited Mega Ion Siege Blaster I, Shadow Antimatter Charge XL
    Limited Mega Ion Siege Blaster I, Shadow Antimatter Charge XL
    Limited Mega Ion Siege Blaster I, Shadow Antimatter Charge XL

    Capital Trimark Armor Pump I
    Capital Trimark Armor Pump I
    Capital Trimark Armor Pump I

**Comment by OISumeko** [comment] 2015-02-24 00:26
Disabling stagger on the cap simulator fixes this issue, giving it the expected behaviour in-line with what other fitting tools suggest. However disabling this does adversely affect some other fits, giving them much more pessimistic cap lives. 

This lower cap life is expected, as activating all modules simultaneously will take larger chunks from your cap and drop you below peak recharge easier than staggering the activation would, but it isn't an ideal presentation. I will have a look over the cap simulation code to see if I can find a way of fixing this without disabling staggering.

**Comment by blitzmann** [comment] 2015-02-24 17:11
Excellent find. Perhaps in the fit class, check if we're dealing with a capacitor booster (or the group) and change the stagger based on that. Im at work righ now so i can see if this works later today ortomorrow. We dhould also have kadesh sign off on it. =)

**Comment by blitzmann** [comment] 2015-02-24 22:21
Disregard my previous comment, was sending off a quick reply on my phone and forgot that this isn't just about cap boosters - it also affects other modules. The way that it is staggered is probably very simple, and the discrepancies we get with modules and cap is simply a by-product of bad chance staggering. Might not be anything that we can do about it, except perhaps make it an option to stagger cap (which might be beneficial in real-world scenarios)

**Comment by BlckKnght** [comment] 2015-03-31 20:02
I've recently been bitten by this issue.

Looking into the code, it seems the issue with staggering is that it doesn't take reload times into account. So, if you have two cap boosters, it cuts the cycle time in half, but does not change the reload time nor the number of cycles between reloads. If your boosters have only a single charge in them (which is common with medium boosters and 800 charges), this breaks the calculation rather badly, since the simulation gives you one boost every 16 seconds instead of every 11 seconds ((12 sec cycle time + 10 sec reload) / 2 modules). If you have more charges per module, the effect is a bit less, but still very wrong.

The only way I can think of getting staggered activation and reloading to work properly in the simulation is to split the merged modules up and add each one in a separate starting place in the priority queue. The pull request above has new code that does this.

**Comment by DarkFenX** [comment] 2015-04-28 16:45
Fixed in a3c19f6f2b6f2654475c3e8d20dc408c146e8f6d

**Closed by DarkFenX** 2015-04-28 16:45 UTC
