### ISSUE TITLE
Missile guidance scripts do not remove the other bonus

### ISSUE THREAD

**Issue by oskar94** [DarkFenX/Pyfa#404] opened 2015-11-05 14:59 UTC
After doing some fitting with MGC's I noticed that even when I scriped for precision the range changed. By looking at the 'Affected by' tab on the missiles i could see that the stats of the MGC increased when the script was loaded but the other bonus was still the same as with no scrip in.

**Comment by blitzmann** [comment] 2015-11-06 01:35
This is a duplicate of #406, in which `0`-valued modifiers don't work correctly. It's been fixed in the repo. =)

**Closed by blitzmann** 2015-11-06 01:35 UTC
