### ISSUE TITLE
[Bug report] Crash when deleting loadout & undeletable loadout

### ISSUE THREAD

**Issue by zanglebert** [DarkFenX/Pyfa#297] opened 2015-06-05 11:20 UTC
Hey.

System: OSX 10.10.3
Pyfa 1.12.0 stable (but problem was present in previous build too).

(1.1) Pyfa regularly crashes for me when trying to  delete loadouts. 

Not 100% how to reproduce, but it seems to happen most reliably when I have the loadout open in the current window when deleting it.

(1.2) Related, perhaps: there are loadouts that I cannot delete, and not open either. It appears under the ship type, I can see it in the xml file, but if I try to open it in pyfa, the window stays empty, and deleting it doesn't work either.

**Comment by blitzmann** [comment] 2015-06-05 17:05
1) seems to be a duplicate of #164. We're still not sure why it happens - I'm hoping that switching to wx3 may help with it, but I haven't had a chance to test is, especially since reproduction is a bit spotty. It's also been reported that it happens sometimes when NOT viewing the fit, so... yeah, not sure.

2) A fit not opening is usually a sign of a module attached to that fit that is no longer in the game. With CCPs recent effort of module teiricide where they rename modules and even remove some from the game, we developed a system that converts old modules to the new ones. Before this, it was rare for CCP to touch existing modules, but it did happen occasionally, and pyfa will crash trying to load a module that did not exist (this is something we've been meaning to fix really). If you have an old database with fits from a few years ago, this is likely what is happening.

However, deleting it should work. Not sure why it doesn't. Could you send me an email at `sable.blitzmannATgmailDOTcom` and attach your database (`~/.pyfa/saveddata.db`). Tell me which ship your trying to load that fails, and I can look into it for you.

**Comment by blitzmann** [comment] 2015-07-05 17:26
I'm going to close this issue. #1 is almost definitely #164. If you can run pyfa from the python interpreter on OS X and verify if it segfaults when deleting, that would be great. We still haven't really found an answer to this though. I've noticed that there are a few places in wxPython that seg fault when you `Destroy()` something (like we destroy the page being deleted). Anyway, if you can verify that seg fault, please follow the discussion in the other issue.

As for #2, it is most likely incorrect modules in the database that are trying to be loaded. We forgot to convert the items that were changes in Carnyx - this will be done with the next release. In addition, the next release has more robust handling of fits with invalid objects, so pyfa should crash anymore when trying to view them (it will simply delete invalid objects found)

**Closed by blitzmann** 2015-07-05 17:26 UTC

**Comment by zanglebert** [comment] 2015-07-13 14:40
@blitzmann Hey. Sorry, forgot about this issue. Just checked it again, and with the latest build I cannot reproduce either issue, i.e. neither did deleting fits while open crash pyfa, nor did empty fit become undeletable. Will report back to issue #164  if the first problem reappears.
