### ISSUE TITLE
[WX3] Error on startup after upgrade from 1.10.0

### ISSUE THREAD

**Issue by tmikoss** [DarkFenX/Pyfa#288] opened 2015-05-07 21:04 UTC
![untitled](https://cloud.githubusercontent.com/assets/222126/7525853/99d83440-f515-11e4-8dff-941bb1288434.png)

Win 8.1, no python-related dev tools installed, upgraded from 1.10.0 via windows-exe installation, without deleting any files. Let me know if you need additional information.

**Comment by blitzmann** [comment] 2015-05-09 08:22
i believe the NoneType error was already corrected, but to be sure I'll wait for Kadesh to close this.

**Comment by DarkFenX** [comment] 2015-05-26 16:08
Remove existing pyfa installation manually (by deleting folder in program files) and reinstall. It seems to be caused by installer not removing old files. Bug itself should be fixed already.

If it doesn't help, reopen issue.

**Closed by DarkFenX** 2015-05-26 16:08 UTC
