### ISSUE TITLE
ancillary shield boosters consume cap while charges are loaded

### ISSUE THREAD

**Issue by sup3rb** [DarkFenX/Pyfa#411] opened 2015-11-06 22:11 UTC
ancillary shield boosters consume cap while charges are loaded

**Comment by blitzmann** [comment] 2015-11-06 23:29
I cannot reproduce. First screen shows MASB with charges loaded. Note that the cap is stable, and the charges do not have a value in the capacitor column. The second screen shows one without the charges. The cap is no longer stable, and the capacitor column shows the cap drain for that module.

![charges](https://cloud.githubusercontent.com/assets/3904767/11011228/fe2c9570-84b3-11e5-89bf-85a9db991eb2.PNG)

![no charges](https://cloud.githubusercontent.com/assets/3904767/11011233/02694ba6-84b4-11e5-8961-355d14bdee3f.PNG)

Please double check your fit. If you are still experiencing issues, please post the fit in question. Screenshots would also be helpful =)

**Comment by sup3rb** [comment] 2015-11-07 01:02
Here's a screenshot with two ASBs.  One is loaded and consumes 15.4, the unloaded consumes 59.4.

![asb capacitor](https://cloud.githubusercontent.com/assets/15696875/11012388/e650476c-84b8-11e5-8a94-d4d10aa4a016.PNG)

**Comment by blitzmann** [comment] 2015-11-07 01:28
Ah, okay. Yeah, this is another manifestation of #406, where the charge is supposed to zero out the cap cost, but the zeroing out doesn't work. It's already  been fixed in the repo (which is why I didn't notice on my test)

**Closed by blitzmann** 2015-11-07 01:28 UTC
