### ISSUE TITLE
Damage pattern editor brakes "Uniform" pattern

### ISSUE THREAD

**Issue by unti1x** [DarkFenX/Pyfa#268] opened 2015-03-25 21:25 UTC
1. Open damage pattern editor
2. Create new pattern
3. ???
4. PROFIT: Your "Uniform" set to all zeros

![no-uni](https://cloud.githubusercontent.com/assets/3488839/6835860/8a6437ae-d34e-11e4-871a-6b05e53bdc2c.png)

Temporary solution: create new uniform-like pattern.

Tested on Win7, Win8.1, found since Pyfa 1.9.0 (earlier versions not tested)

**Comment by blitzmann** [comment] 2015-03-25 22:28
Why the hell is everyone finding out about this bug in in just the last three days?

This is a duplicate of #267, which has been fixed in 1.10.0. Before upgrading, make sure you fix the uniform pattern first:
Click Create button -> name it "Uniform" -> HIT ENTER (do not hit the create button), set values to 25, 25, 25, 25. Confirm that it works. Then upgrade to 1.10.0. =)

**Comment by unti1x** [comment] 2015-03-28 20:32
Bug is still can be reproduced. It sets to null all the values of active pattern

**Comment by blitzmann** [comment] 2015-03-29 04:23
You're right! There were about 3 or 4 bugs revolving around the pattern editor that were all reported within 2 days of the latest release, yours included. This looked extremely similar to the previous bugs.

Will look into it. =)

**Closed** 2015-04-09 03:44 UTC
