### ISSUE TITLE
Traceback when working with t3ds

### ISSUE THREAD

**Issue by DarkFenX** [DarkFenX/Pyfa#323] opened 2015-07-09 20:28 UTC
Confessor:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/dfx/src/eve/pyfa/service/market.py", line 75, in run
    self.processUpdates()
  File "/home/dfx/src/eve/pyfa/service/market.py", line 85, in processUpdates
    service.Price.fetchPrices(requests)
  File "/home/dfx/src/eve/pyfa/service/price.py", line 55, in fetchPrices
    if item.marketGroupID:
AttributeError: 'NoneType' object has no attribute 'marketGroupID'
```
Seems like it still attempts to fetch price for t3d mode? Just doesn't put item there anymore, but puts None.

**Comment by blitzmann** [comment] 2015-07-09 22:04
I cannot reproduce. Returning `None` is the same way empty module slots handle not getting a price. In any case, doesn't make sense as the mode shouldn't be added to the price fetching queue. I think this may have something to do with the other issue you posted - #324. Something weird indeed

**Comment by DarkFenX** [comment] 2015-07-09 22:07
Yeah, just make t3d fit, fit some gun to it and move it to another slot.

**Comment by blitzmann** [comment] 2015-07-09 22:41
k, so I have no idea why this happens, but I committed a check to make sure item is not None. That should hopefully work

**Closed by blitzmann** 2015-07-09 22:41 UTC
