### ISSUE TITLE
Blank logs

### ISSUE THREAD

**Issue by thorr18** [DarkFenX/Pyfa#448] opened 2015-11-28 12:41 UTC
My log files are blank on 1.16.x, but not on 1.15. The file gets created, but left empty. Maybe this is by design? I tested again intentionally causing the submenu-in-submenu error on 1.16.2, but the log was again blank even after crash, which I did not expect!
Don't want to be a nuisance, but maybe it'd be good to have logs from troubled users.
~~~
BsMBP:tests bem$ ./testForPyfaLogs.sh 
rm: /Users/bem/.pyfa/log.txt: No such file or directory


***Running: pyfa1162noWx3.app
***pyfa exited; log contents below: 
***^^^


***Running: pyfa1162.app
***pyfa exited; log contents below: 
***^^^


***Running: pyfa1161.app
***pyfa exited; log contents below: 
***^^^


***Running: pyfa1150.app
2015-11-28 04:19:04,834 STDERR                   ERROR    Traceback (most recent call last):
2015-11-28 04:19:04,834 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1150.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14640, in <lambda>
2015-11-28 04:19:04,837 STDERR                   ERROR    lambda event: event.callable(*event.args, **event.kw) )
2015-11-28 04:19:04,837 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1150.app/Contents/Resources/gui/mainFrame.py", line 205, in ShowUpdateBox
2015-11-28 04:19:04,837 STDERR                   ERROR    dlg.Destroy()
2015-11-28 04:19:04,837 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1150.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14590, in __getattr__
2015-11-28 04:19:04,839 STDERR                   ERROR    raise PyDeadObjectError(self.attrStr % self._name)
2015-11-28 04:19:04,840 STDERR                   ERROR    wx._core
2015-11-28 04:19:04,840 STDERR                   ERROR    .
2015-11-28 04:19:04,840 STDERR                   ERROR    PyDeadObjectError
2015-11-28 04:19:04,840 STDERR                   ERROR    :
2015-11-28 04:19:04,840 STDERR                   ERROR    The C++ part of the UpdateDialog object has been deleted, attribute access no longer allowed.
***pyfa exited; log contents below: 
2015-11-28 04:19:04,834 STDERR                   ERROR    Traceback (most recent call last):
2015-11-28 04:19:04,834 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1150.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14640, in <lambda>
2015-11-28 04:19:04,837 STDERR                   ERROR    lambda event: event.callable(*event.args, **event.kw) )
2015-11-28 04:19:04,837 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1150.app/Contents/Resources/gui/mainFrame.py", line 205, in ShowUpdateBox
2015-11-28 04:19:04,837 STDERR                   ERROR    dlg.Destroy()
2015-11-28 04:19:04,837 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1150.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14590, in __getattr__
2015-11-28 04:19:04,839 STDERR                   ERROR    raise PyDeadObjectError(self.attrStr % self._name)
2015-11-28 04:19:04,840 STDERR                   ERROR    wx._core
2015-11-28 04:19:04,840 STDERR                   ERROR    .
2015-11-28 04:19:04,840 STDERR                   ERROR    PyDeadObjectError
2015-11-28 04:19:04,840 STDERR                   ERROR    :
2015-11-28 04:19:04,840 STDERR                   ERROR    The C++ part of the UpdateDialog object has been deleted, attribute access no longer allowed.
***^^^


***Running: pyfa1133.app
2015-11-28 04:19:07,352 root                     INFO     Starting pyfa
2015-11-28 04:19:09,037 STDOUT                   INFO     Not projected, getting projected fits
2015-11-28 04:19:09,038 service.fit              DEBUG    ==========recalc==========
2015-11-28 04:19:09,090 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=8, ship=Slasher, name=Slasher fit) at 0xd975850
2015-11-28 04:19:09,172 eos.saveddata.fit        DEBUG    Timer - Fit: 8, Slasher fit - Done with runtime: early - 82.61ms (82.62ms elapsed)
2015-11-28 04:19:09,212 eos.saveddata.fit        DEBUG    Timer - Fit: 8, Slasher fit - Done with runtime: normal - 40.21ms (122.84ms elapsed)
2015-11-28 04:19:09,219 eos.saveddata.fit        DEBUG    Timer - Fit: 8, Slasher fit - Done with runtime: late - 6.98ms (129.83ms elapsed)
2015-11-28 04:19:09,220 eos.saveddata.fit        DEBUG    Timer - Fit: 8, Slasher fit - Done with fit calculation - 0.14ms (129.98ms elapsed)
2015-11-28 04:19:12,585 STDERR                   ERROR    Traceback (most recent call last):
2015-11-28 04:19:12,585 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1133.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14640, in <lambda>
2015-11-28 04:19:12,587 STDERR                   ERROR    lambda event: event.callable(*event.args, **event.kw) )
2015-11-28 04:19:12,588 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1133.app/Contents/Resources/gui/mainFrame.py", line 205, in ShowUpdateBox
2015-11-28 04:19:12,588 STDERR                   ERROR    dlg.Destroy()
2015-11-28 04:19:12,588 STDERR                   ERROR      File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1133.app/Contents/Resources/lib/python2.7/wx/_core.py", line 14590, in __getattr__
2015-11-28 04:19:12,590 STDERR                   ERROR    raise PyDeadObjectError(self.attrStr % self._name)
2015-11-28 04:19:12,590 STDERR                   ERROR    wx._core
2015-11-28 04:19:12,590 STDERR                   ERROR    .
2015-11-28 04:19:12,590 STDERR                   ERROR    PyDeadObjectError
2015-11-28 04:19:12,590 STDERR                   ERROR    :
2015-11-28 04:19:12,590 STDERR                   ERROR    The C++ part of the UpdateDialog object has been deleted, attribute access no longer allowed.
***pyfa exited; log contents below: 
cat: /Users/bem/.pyfa/log.txt: No such file or directory
***^^^
mv: rename /Users/bem/.pyfa/log.txt to /Users/bem/.pyfa/pyfa1133.app.log: No such file or directory


***Running: pyfa-preRelease.app
***pyfa exited; log contents below: 
***^^^

***Displaying log sizes: 
0 /Users/bem/.pyfa/pyfa-preRelease.app.log
4 /Users/bem/.pyfa/pyfa1150.app.log
0 /Users/bem/.pyfa/pyfa1161.app.log
0 /Users/bem/.pyfa/pyfa1162.app.log
0 /Users/bem/.pyfa/pyfa1162noWx3.app.log
BsMBP:tests bem$ 
~~~

So I got only 1 log file that's not size zero. 

my test was done on OSX 10.11.1: 
~~~
BsMBP:tests bem$ cat ./testForPyfaLogs.sh
#testForPyfaLogs.sh iterates through the downloaded builds to compare 

rm ~/.pyfa/log.txt
rm ~/.pyfa/*.log
for p in `ls -r ../dloadedBuilds/`
do
  printf "\r\n\r\n***Running: $p\r\n"
#  open ../dloadedBuilds/$p --args -d
  ../dloadedBuilds/$p/Contents/MacOS/pyfa
  echo "***pyfa exited; log contents below: "
  cat ~/.pyfa/log.txt
  echo "***^^^"
  mv ~/.pyfa/log.txt ~/.pyfa/$p.log
done
printf "\r\n***Displaying log sizes: \r\n"
ls -1skh ~/.pyfa/*.log
#
BsMBP:tests bem$ 
~~~

**Comment by blitzmann** [comment] 2015-11-28 22:50
I haven't tried it, but I would not be surprised if log files didn't work. Log files have never really worked correctly with pyfa.

A few notes tho:
* Unless you're running with the debug flag, you probably won't get any output except with errors
* That being said, the reason (probably) you didn't get an error when reproducing the right click bug is because that was an assertion error in the linked library. Since it didn't technically come from the python code, it wasn't logged. It's a subtle but (maybe) important difference. (I actually barely know what I'm talking about with this <_<)
* log.txt is relatively new. Things used to go to error_log.txt and output_log.txt until I combined them. That might be why 1.13 didn't output any logs?

But yeah, I should probably double check that logs are working.

**Comment by thorr18** [comment] 2015-11-29 01:59
I see. 
So adding the debug flag did generate logs for the versions that accepted the flag. Debug level statements and above are in the log. 
~~~
***Displaying log sizes: 
4 /Users/bem/.pyfa/pyfa-preRelease.app.log
4 /Users/bem/.pyfa/pyfa1161.app.log
4 /Users/bem/.pyfa/pyfa1162.app.log
4 /Users/bem/.pyfa/pyfa1162noWx3.app.log
~~~

Maybe later I could play around and add some logging changes, like perhaps showing what version has been started and what level is being logged.

**Comment by thorr18** [comment] 2015-11-29 02:59
Just tried it on my Chromebook and it was the same. Debug flag has to be on to at least log the "Starting pyfa" message. That Info level doesn't even output to terminal without it, except back on 1.13
Really, I had wrongly assumed it was another OSX specific issue, which is why I reported it.

**Comment by blitzmann** [comment] 2015-11-29 03:30
https://docs.python.org/2/library/logging.html#logging-levels

Even though Info is higher than Debug, it is lower than Warn, which is the default value if no flagging is set and hence why the info log didn't write. Setting debug is just the easy way to say "log everything", including info (info is usually not really important information)

Gonna close this issue as it seems to be working as intended =)

Also, pyfa works on a chromebook? Holy hell, I should add that to the list of supported platforms

**Closed by blitzmann** 2015-11-29 03:30 UTC

**Comment by thorr18** [comment] 2015-11-29 04:44
Alright, just as long as not logging assertion errors from linked libraries is intended behavior :)
