### ISSUE TITLE
Crucifier hull bonus / Particle Dispersion Projectors don't affect TD optimal range

### ISSUE THREAD

**Issue by ullerrm** [DarkFenX/Pyfa#462] opened 2015-12-05 18:55 UTC
Create a Crucifier with a TD.  You should see 108km+36km range; shows 72km range instead.
Then, add a Small Particle Dispersion Projector.  Should go up to 130+36km; instead, has no effect.

Worked in 1.16.2; does not work on current git build.

Note: The rig's ewSkillTpMaxRangeBonus is referencing a non-existent attribute, rangeSkillBonus.  No clue why Crucifier bonus isn't working, though.

**Comment by blitzmann** [comment] 2015-12-06 03:43
The sisi branch had some bugs as it related to TD's which was caused by a skill book rename. It was fixed as of ca92285ff3794ec9638f7fe94212c8e59be11b08

BTW, the rig does have a `rangeSkillBonus` attribute, which is used to modify the `maxRange` attribute of affected modules.

**Closed by blitzmann** 2015-12-06 03:43 UTC
