### ISSUE TITLE
Compatibility Issues after python2-sqlalchemy 1.0.0

### ISSUE THREAD

**Issue by MagicFish1990** [DarkFenX/Pyfa#277] opened 2015-04-27 00:31 UTC
SQL processing failed, without any errors.

**Comment by DarkFenX** [comment] 2015-04-29 14:38
Sounds weird. I've been playing a bit with it (on windows, after merging wx3 branch) and 1.0.2 worked just fine for me.

**Comment by DarkFenX** [comment] 2015-04-29 14:38
Please specify at least exact version of sql alchemy and OS you're using.

**Comment by MagicFish1990** [comment] 2015-04-29 16:32
pyfa 1.11.0.r16.gbb8d5d0
python2-sqlalchemy 1.0.0-1.0.2
Archlinux

**Comment by MagicFish1990** [comment] 2015-04-29 16:35
Part of error

Traceback (most recent call last):
  File "/usr/share/pyfa/gui/sfBrowserItem.py", line 318, in OnLeftUp
    btn.DoCallback()
  File "/usr/share/pyfa/gui/sfBrowserItem.py", line 49, in DoCallback
    self.callback()
  File "/usr/share/pyfa/gui/shipBrowser.py", line 1608, in copyBtnCB
    self.copyFit()
  File "/usr/share/pyfa/gui/shipBrowser.py", line 1612, in copyFit
    fitID = sFit.copyFit(self.fitID)
  File "/usr/share/pyfa/service/fit.py", line 184, in copyFit
    eos.db.save(newFit)
  File "/usr/share/pyfa/eos/db/saveddata/queries.py", line 415, in save
    commit()
  File "/usr/share/pyfa/eos/db/saveddata/queries.py", line 426, in commit
    saveddata_session.commit()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 487, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 755, in process_saves
    uowcommit, "add")
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 775, in _synchronize
    sync.clear(state, self.parent, self.prop.synchronize_pairs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/sync.py", line 77, in clear
    dest_mapper._set_state_attr_by_column(dest, dest.dict, r, None)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2426, in _set_state_attr_by_column
    state.manager[prop.key].impl.set(state, dict_, value, None)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 696, in set
    value, old, initiator)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 705, in fire_replace_event
    self._init_append_or_replace_token())
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/util.py", line 118, in set_
    return validator(state.obj(), key, value)
  File "/usr/share/pyfa/eos/saveddata/fit.py", line 301, in validator
    if map[key](val) == False: raise ValueError(str(val) + " is not a valid value for " + key)
ValueError: None is not a valid value for ownerID

**Comment by MagicFish1990** [comment] 2015-04-29 16:42
If I remove pyfa current user's profile, pyfa will not start. It looks creating database failed.
If I downgrade sqlalchemy to 0.9.9, everything is fine.

**Comment by blitzmann** [comment] 2015-04-29 21:57
So, you're trying to copy a fit when you experience the error? Have you run into any other crashes while using pyfa? What's the traceback when you don't have a user profile and it crashes?

Also possible duplicate of #274

**Comment by MagicFish1990** [comment] 2015-04-29 23:19
If I do not have user profile/database, pyfa just create an incomplete database, and then exit. No GUI, no log.

> pyfa
19:15:06: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).

exit.

Actually only database read function works. It cannot save, and data is wrong.

**Comment by DarkFenX** [comment] 2015-04-30 17:00
Uhh, i recently got a PM on russian forums with exactly the same issue.

Pyfa has nothing to do with ABI (unless it's ABI incompatibility of the libs we provide with distributions). Seems like Arch broke stuff somewhere.

**Comment by wolfwood** [comment] 2015-05-27 06:16
I'm also seeing this "if mapkey == False: raise ValueError(str(val) + " is not a valid value for " + key)
ValueError: None is not a valid value for ownerID" issue on gentoo with both pyfa 1.9 and 1.11, on two separate machines.

**Comment by DarkFenX** [comment] 2015-05-27 11:56
Check #274 and try pulling latest changes. If it doesn't work - reopen issue.

**Closed by DarkFenX** 2015-05-27 11:56 UTC
